# coding: utf-8
#
# user-graph need to be generated by the following script
# tools/generate-u-u-matrix.py
import os
import numpy as np
import scipy.sparse as sp
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import remove_self_loops, add_self_loops, degree
import torch_geometric
from logging import getLogger

from common.abstract_recommender import GeneralRecommender
from common.loss import BPRLoss, EmbLoss
from common.init import xavier_uniform_initialization

class PEARL(GeneralRecommender):
    def __init__(self, config, dataset):
        super(PEARL, self).__init__(config, dataset)

        num_user = self.n_users
        num_item = self.n_items
        self.n_nodes = self.n_users + self.n_items
        batch_size = config['train_batch_size']  # not used
        dim_x = config['embedding_size']
        self.feat_embed_dim = config['feat_embed_dim']
        self.n_layers = config['n_mm_layers']
        self.n_layers_u = config['n_layers']
        self.knn_k = config['knn_k']
        self.knn_k_u = config['knn_k_u']
        self.mm_image_weight = config['mm_image_weight']
        has_id = True

        self.num_user = num_user
        self.num_item = num_item
        self.aggr_mode = config['aggr_mode']
        self.dataset = dataset
        # self.construction = 'weighted_max'
        self.reg_weight = config['reg_weight']
        self.drop_rate = 0.1
        self.v_rep = None
        self.t_rep = None
        self.v_preference = None
        self.t_preference = None
        self.dim_latent = 64
        self.temp = config['temp']
        self.drop_g = config['drop_g']
        self.dropout = config['pure_drop']
        self.cl_weight = config['cl_weight']


        # load dataset info
        self.interaction_matrix = dataset.inter_matrix(form='coo').astype(np.float32)
        self.G_adj, self.D_row_mat, self.D_col_mat = self.d_col()

        dataset_path = os.path.abspath(config['data_path'] + config['dataset'])

        # mm_adj_file = os.path.join(dataset_path + '\mat', 'mm_adj_{}.pt'.format(self.knn_k))
        ii_v_mat_file = os.path.join(dataset_path + '\mat', 'ii_v_mat_{}.pt'.format(self.knn_k))
        ii_t_mat_file = os.path.join(dataset_path + '\mat', 'ii_t_mat_{}.pt'.format(self.knn_k))
        ii_mat_file = os.path.join(dataset_path + '\mat', 'ii_mat_{}_{}.pt'.format(self.knn_k, self.mm_image_weight))
        if self.v_feat is not None:
            self.image_embedding = nn.Embedding.from_pretrained(self.v_feat, freeze=False)
            self.image_trs = nn.Linear(self.v_feat.shape[1], self.feat_embed_dim)
        if self.t_feat is not None:
            self.text_embedding = nn.Embedding.from_pretrained(self.t_feat, freeze=False)
            self.text_trs = nn.Linear(self.t_feat.shape[1], self.feat_embed_dim)

        if os.path.exists(ii_mat_file):
            # self.mm_adj = torch.load(mm_adj_file)
            self.ii_v_mat = torch.load(ii_v_mat_file)
            self.ii_t_mat = torch.load(ii_t_mat_file)
            self.ii_mat = torch.load(ii_mat_file)
        else:
            image_adj = self.get_knn_adj_mat(self.image_embedding.weight.detach())
            self.ii_v_mat = image_adj
            text_adj = self.get_knn_adj_mat(self.text_embedding.weight.detach())
            self.ii_t_mat = text_adj
            self.ii_mat = self.mm_image_weight * image_adj + text_adj
            del text_adj
            del image_adj
            torch.save(self.ii_v_mat, ii_v_mat_file)
            torch.save(self.ii_t_mat, ii_t_mat_file)
            torch.save(self.ii_mat, ii_mat_file)

        uu_mat_file = os.path.join(dataset_path + '\mat', 'uu_mat_{}.pt'.format(self.knn_k_u))
        if os.path.exists(uu_mat_file):
            self.uu_mat = torch.load(uu_mat_file)
        else:
            uu_mat = self.get_knn_adj_mat_u(self.knn_k_u)
            self.uu_mat = uu_mat
            torch.save(self.uu_mat, uu_mat_file)


        # packing interaction in training into edge_index
        train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)
        edge_index = self.pack_edge_index(train_interactions)
        self.edge_index = torch.tensor(edge_index, dtype=torch.long).t().contiguous().to(self.device)
        # self.edge_index = torch.cat((self.edge_index, self.edge_index[[1, 0]]), dim=1)
        self.edge_index_v = torch.cat((self.edge_index, self.edge_index[[1, 0]]), dim=1)
        self.edge_index_t = torch.cat((self.edge_index, self.edge_index[[1, 0]]), dim=1)

        # pdb.set_trace()
        self.weight_u = nn.Parameter(nn.init.xavier_normal_(
            torch.tensor(np.random.randn(self.num_user, 2, 1), dtype=torch.float32, requires_grad=True)))
        self.weight_u.data = F.softmax(self.weight_u, dim=1)

        self.weight_i = nn.Parameter(nn.init.xavier_normal_(
            torch.tensor(np.random.randn(self.num_item, 2, 1), dtype=torch.float32, requires_grad=True)))
        self.weight_i.data = F.softmax(self.weight_i, dim=1)

        self.item_index = torch.zeros([self.num_item], dtype=torch.long)
        index = []
        for i in range(self.num_item):
            self.item_index[i] = i
            index.append(i)
        self.drop_percent = self.drop_rate
        self.single_percent = 1
        self.double_percent = 0

        drop_item = torch.tensor(
            np.random.choice(self.item_index, int(self.num_item * self.drop_percent), replace=False))
        drop_item_single = drop_item[:int(self.single_percent * len(drop_item))]

        self.dropv_node_idx_single = drop_item_single[:int(len(drop_item_single) * 1 / 3)]
        self.dropt_node_idx_single = drop_item_single[int(len(drop_item_single) * 2 / 3):]

        self.dropv_node_idx = self.dropv_node_idx_single
        self.dropt_node_idx = self.dropt_node_idx_single

        mask_cnt = torch.zeros(self.num_item, dtype=int).tolist()
        for edge in edge_index:
            mask_cnt[edge[1] - self.num_user] += 1
        mask_dropv = []
        mask_dropt = []
        for idx, num in enumerate(mask_cnt):
            temp_false = [False] * num
            temp_true = [True] * num
            mask_dropv.extend(temp_false) if idx in self.dropv_node_idx else mask_dropv.extend(temp_true)
            mask_dropt.extend(temp_false) if idx in self.dropt_node_idx else mask_dropt.extend(temp_true)

        edge_index = edge_index[np.lexsort(edge_index.T[1, None])]
        edge_index_dropv = edge_index[mask_dropv]
        edge_index_dropt = edge_index[mask_dropt]

        self.edge_index_dropv = torch.tensor(edge_index_dropv).t().contiguous().to(self.device)
        self.edge_index_dropt = torch.tensor(edge_index_dropt).t().contiguous().to(self.device)

        self.edge_index_dropv = torch.cat((self.edge_index_dropv, self.edge_index_dropv[[1, 0]]), dim=1)
        self.edge_index_dropt = torch.cat((self.edge_index_dropt, self.edge_index_dropt[[1, 0]]), dim=1)


        if self.v_feat is not None:
            self.v_drop_ze = torch.zeros(len(self.dropv_node_idx), self.v_feat.size(1)).to(self.device)
            self.v_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                             num_layer=self.n_layers_u, has_id=has_id, dropout=self.drop_rate, dim_latent=64,
                             device=self.device, features=self.v_feat)  # 256)
        if self.t_feat is not None:
            self.t_drop_ze = torch.zeros(len(self.dropt_node_idx), self.t_feat.size(1)).to(self.device)
            self.t_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                             num_layer=self.n_layers_u, has_id=has_id, dropout=self.drop_rate, dim_latent=64,
                             device=self.device, features=self.t_feat)

        self.result_embed = nn.Parameter(
            nn.init.xavier_normal_(torch.tensor(np.random.randn(num_user + num_item, dim_x)))).to(self.device)

        self.user_embedding = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
            np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
            gain=1).to(self.device))

        self.item_embedding = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
            np.random.randn(num_item, self.dim_latent), dtype=torch.float32, requires_grad=True),
            gain=1).to(self.device))

        self.edge_indices, self.edge_values = self.get_edge_info()
        self.edge_indices, self.edge_values = self.edge_indices.to(self.device), self.edge_values.to(self.device)

        self.norm_adj = self.get_norm_adj_mat().to(self.device)

    def d_col(self):
        #获得交互图的tensor矩阵表达
        G_m = sp.dok_matrix((self.n_users, self.n_items), dtype=np.float32)
        inter_G_m = self.interaction_matrix
        data_dict = dict(zip(zip(inter_G_m.row, inter_G_m.col), [1] * inter_G_m.nnz))
        G_m._update(data_dict)
        G_m = sp.coo_matrix(G_m)
        G_adj = torch.sparse.FloatTensor(torch.LongTensor(np.array([G_m.row, G_m.col])),
                                         torch.FloatTensor(G_m.data), torch.Size((self.n_users, self.n_items))).to(self.device)

        sumArr_row = (G_m > 0).sum(axis=1)
        D_row = sp.coo_matrix(sp.diags(np.power(np.array(sumArr_row.flatten())[0] + 1e-7, -0.5)))
        D_row_adj = torch.sparse.FloatTensor(torch.LongTensor(np.array([D_row .row, D_row .col])),
                                         torch.FloatTensor(D_row .data), torch.Size((self.n_users, self.n_users))).to(self.device)
        sumArr_col = (G_m > 0).sum(axis=0)
        D_col= sp.coo_matrix(sp.diags(np.power(np.array(sumArr_col.flatten())[0] + 1e-7, -0.5)))
        D_col_adj = torch.sparse.FloatTensor(torch.LongTensor(np.array([D_col.row, D_col.col])),
                                         torch.FloatTensor(D_col.data), torch.Size((self.n_items, self.n_items))).to(self.device)

        return G_adj, torch.sparse.mm(D_row_adj, G_adj), torch.sparse.mm(D_col_adj, G_adj.T)

    def get_edge_info(self):
        rows = torch.from_numpy(self.interaction_matrix.row)
        cols = torch.from_numpy(self.interaction_matrix.col)
        edges = torch.stack([rows, cols]).type(torch.LongTensor)
        # edge normalized values
        values = self.normalize_adj_g(edges, torch.Size((self.n_users, self.n_items)))
        return edges, values

    def get_knn_adj_mat(self, mm_embeddings):
        context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
        adj_size = sim.size()
        del sim
        # construct sparse adj
        indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
        indices0 = torch.unsqueeze(indices0, 1)
        indices0 = indices0.expand(-1, self.knn_k)
        indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
        # norm
        return self.compute_normalized_laplacian(indices, adj_size)

    def get_knn_adj_mat_u(self, knn):
        G_m = sp.dok_matrix((self.n_users, self.n_items), dtype=np.float32)
        inter_G_m = self.interaction_matrix
        data_dict = dict(zip(zip(inter_G_m.row, inter_G_m.col), [1] * inter_G_m.nnz))
        G_m._update(data_dict)
        G_m = sp.coo_matrix(G_m)
        G_adj = torch.sparse.FloatTensor(torch.LongTensor(np.array([G_m.row, G_m.col])),
                                         torch.FloatTensor(G_m.data), torch.Size((self.n_users, self.n_items))).to(self.device)
        context_norm = G_adj.to_dense()
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        mid_index = sim.size(0) // 2
        sim1 = sim[:mid_index, :]
        sim2 = sim[mid_index:, :]
        _, knn_ind1 = torch.topk(sim1, knn, dim=-1)
        _, knn_ind2 = torch.topk(sim2, knn, dim=-1)
        knn_ind = torch.cat((knn_ind1, knn_ind2), dim=0)
        adj_size = sim.size()
        del sim, sim1, sim2
        # construct sparse adj
        indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
        indices0 = torch.unsqueeze(indices0, 1)
        indices0 = indices0.expand(-1, knn)
        indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
        # norm
        return self.compute_normalized_laplacian(indices, adj_size)

    def compute_normalized_laplacian(self, indices, adj_size):
        adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
        row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
        r_inv_sqrt = torch.pow(row_sum, -0.5)
        rows_inv_sqrt = r_inv_sqrt[indices[0]]
        cols_inv_sqrt = r_inv_sqrt[indices[1]]
        values = rows_inv_sqrt * cols_inv_sqrt
        return torch.sparse.FloatTensor(indices, values, adj_size)

    def pre_epoch_processing(self):

        return

    def pack_edge_index(self, inter_mat):
        rows = inter_mat.row
        cols = inter_mat.col + self.n_users
        # ndarray([598918, 2]) for ml-imdb
        return np.column_stack((rows, cols))

    def hete_GCN(self, mat, embeddings):
        # 异构图卷积
        all_embeddings = [embeddings]
        for i in range(self.n_layers_u):
            side_embeddings = torch.sparse.mm(mat, embeddings)
            embeddings = side_embeddings
            all_embeddings += [embeddings]

        all_embeddings = torch.stack(all_embeddings, dim=1)
        all_embeddings = all_embeddings.sum(dim=1, keepdim=False)
        u_g_embeddings, i_g_embeddings = torch.split(all_embeddings, [self.n_users, self.n_items], dim=0)

        return u_g_embeddings, i_g_embeddings

    def get_norm_adj_mat(self):
        degree_len = int(self.edge_values.size(0) * (1. - self.drop_g))
        degree_idx = torch.multinomial(self.edge_values, degree_len)
        # random sample
        keep_indices = self.edge_indices[:, degree_idx]
        # norm values
        keep_values = self.normalize_adj_g(keep_indices, torch.Size((self.n_users, self.n_items)))
        all_values = torch.cat((keep_values, keep_values))
        # update keep_indices to users/items+self.n_users
        keep_indices[1] += self.n_users
        all_indices = torch.cat((keep_indices, torch.flip(keep_indices, [0])), 1)

        return torch.sparse.FloatTensor(all_indices, all_values, torch.Size((self.n_nodes, self.n_nodes))).to(self.device)

    def normalize_adj_g(self, indices, adj_size):
        adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
        row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
        col_sum = 1e-7 + torch.sparse.sum(adj.t(), -1).to_dense()
        r_inv_sqrt = torch.pow(row_sum, -0.5)
        rows_inv_sqrt = r_inv_sqrt[indices[0]]
        c_inv_sqrt = torch.pow(col_sum, -0.5)
        cols_inv_sqrt = c_inv_sqrt[indices[1]]
        values = rows_inv_sqrt * cols_inv_sqrt
        return values

    def pure_modal_graph(self, items_v, users_v, items_t, users_t):
        # users = users_v * self.mm_image_weight + users_t * (1 - self.mm_image_weight)
        users_v_norm = users_v / torch.norm(users_v, dim=1, keepdim=True)
        users_t_norm = users_t / torch.norm(users_t, dim=1, keepdim=True)
        items_v_norm = items_v / torch.norm(items_v, dim=1, keepdim=True)
        items_t_norm = items_t / torch.norm(items_t, dim=1, keepdim=True)

        degree = self.D_row_mat * self.D_col_mat.t()
        similarity_v = degree * torch.mm(users_v_norm, items_v_norm.t())
        similarity_t = degree * torch.mm(users_t_norm, items_t_norm.t())
        similarity_v_values = self.sparse_softmax(similarity_v)
        similarity_t_values = self.sparse_softmax(similarity_t)

        diff_adj_vt = torch.sparse_coo_tensor(degree._indices(), similarity_v_values-similarity_t_values, size=degree.size())
        diff_adj_tv = torch.sparse_coo_tensor(degree._indices(), similarity_t_values-similarity_v_values, size=degree.size())

        diff_adj = diff_adj_vt + diff_adj_tv
        diff_adj_values = diff_adj._values()
        # 映射到0-1
        normalized_diff_adj_values = torch.sigmoid(diff_adj_values)

        save_len = int(self.G_adj._values().size(0) * (2 - self.dropout))
        save_idx = torch.multinomial(normalized_diff_adj_values, save_len)
        sorted_save_idx, _ = torch.sort(save_idx, dim=0)
        v_id = sorted_save_idx[sorted_save_idx < self.G_adj._values().size(0)]
        t_id = sorted_save_idx[sorted_save_idx >= self.G_adj._values().size(0)] - self.G_adj._values().size(0)

        edge_indices = degree._indices()
        keep_indices_v = edge_indices[:, v_id]
        keep_indices_t = edge_indices[:, t_id]
        keep_indices_v[1] += self.num_user
        keep_indices_t[1] += self.num_user
        keep_indices_v = torch.cat((keep_indices_v, keep_indices_v[[1, 0]]), dim=1)
        keep_indices_t = torch.cat((keep_indices_t, keep_indices_t[[1, 0]]), dim=1)
        return keep_indices_v, keep_indices_t

    def sparse_softmax(self, sparse_tensor):

        indices = sparse_tensor.coalesce()._indices()
        values = sparse_tensor.coalesce()._values()
        size = sparse_tensor.size()
        exp_values = torch.exp(values)
        sum_exp_values = torch.sparse.sum(torch.sparse_coo_tensor(indices, exp_values, size=size), dim=1).to_dense()
        a = sum_exp_values[indices[0]]
        softmax_values = exp_values / sum_exp_values[indices[0]]
        sparse_softmax_output = torch.sparse_coo_tensor(indices, softmax_values, size=size)

        return softmax_values

    def forward(self, interaction):
        user_nodes, pos_item_nodes, neg_item_nodes = interaction[0], interaction[1].clone(), interaction[2].clone()
        pos_item_nodes += self.n_users
        neg_item_nodes += self.n_users
        representation = None

        self.v_rep, self.v_preference, v_feature = self.v_gcn(self.edge_index_dropv, self.edge_index_v, self.v_feat)
        representation_v = self.v_rep
        self.t_rep, self.t_preference, t_feature = self.t_gcn(self.edge_index_dropt, self.edge_index_t, self.t_feat)
        representation_t = self.t_rep

        self.edge_index_v, self.edge_index_t = self.pure_modal_graph(v_feature.detach(),
                                                                     self.v_preference.detach(),
                                                                     t_feature.detach(),
                                                                     self.t_preference.detach())

        user_rep_v = representation_v[:self.num_user]
        user_rep_t = representation_t[:self.num_user]
        item_rep_v = representation_v[self.num_user:]
        item_rep_t = representation_t[self.num_user:]
        id_embedding = torch.cat((self.user_embedding, self.item_embedding), dim=0)
        user_rep, item_rep = self.hete_GCN(self.norm_adj, id_embedding)
        user_rep = F.normalize(user_rep)
        item_rep = F.normalize(item_rep)

        ############################################ multi-modal information aggregation
        h_i_v = item_rep_v
        h_i_t = item_rep_t
        h_i = item_rep
        h_u_v = user_rep_v
        h_u_t = user_rep_t
        h_u = user_rep
        for i in range(self.n_layers):
            h_i_v = torch.sparse.mm(self.ii_v_mat, h_i_v)
            h_i_t = torch.sparse.mm(self.ii_t_mat, h_i_t)
            h_i = torch.sparse.mm(self.ii_mat, h_i)
            h_u_v = torch.sparse.mm(self.uu_mat, h_u_v)
            h_u_t = torch.sparse.mm(self.uu_mat, h_u_t)
            h_u = torch.sparse.mm(self.uu_mat, h_u)

        final_item_rep_v = item_rep_v + h_i_v
        final_item_rep_t = item_rep_t + h_i_t
        final_item_rep = item_rep + h_i
        item = torch.cat((final_item_rep, self.mm_image_weight * final_item_rep_v, (1.0 - self.mm_image_weight) * final_item_rep_t), dim=1)

        final_user_rep_v = user_rep_v + h_u_v
        final_user_rep_t = user_rep_t + h_u_t
        final_user_rep = user_rep + h_u
        atten_user_v = torch.unsqueeze(final_user_rep_v, 2)
        atten_user_t = torch.unsqueeze(final_user_rep_t, 2)
        atten_user = torch.cat((atten_user_v, atten_user_t), dim =2)
        atten_user = self.weight_u.transpose(1, 2) * atten_user
        final_user_rep_v = atten_user[:, :, 0]
        final_user_rep_t = atten_user[:, :, 1]

        user = torch.cat((final_user_rep, final_user_rep_v, final_user_rep_t), dim=1)

        self.result_embed = torch.cat((user, item), dim=0)
        user_tensor = self.result_embed[user_nodes]
        pos_item_tensor = self.result_embed[pos_item_nodes]
        neg_item_tensor = self.result_embed[neg_item_nodes]
        pos_scores = torch.sum(user_tensor * pos_item_tensor, dim=1)
        neg_scores = torch.sum(user_tensor * neg_item_tensor, dim=1)

        pos_user = interaction[0]
        pos_items_cl = interaction[1]
        user_cl = final_user_rep[pos_user]
        user_cl_v = final_user_rep_v[pos_user]
        user_cl_t = final_user_rep_t[pos_user]
        item_cl = final_item_rep[pos_items_cl]
        item_cl_v = final_item_rep_v[pos_items_cl]
        item_cl_t = final_item_rep_t[pos_items_cl]


        cl_loss = self.cl_loss(user_cl, user_cl_v) + self.cl_loss(user_cl, user_cl_t) + self.cl_loss(item_cl, item_cl_v) + self.cl_loss(item_cl, item_cl_t)

        return pos_scores, neg_scores, cl_loss

    def calculate_loss(self, interaction):
        user = interaction[0]
        pos_items = interaction[1]
        neg_items = interaction[2]

        pos_scores, neg_scores, cl_loss = self.forward(interaction)
        loss_value = -torch.mean(torch.log2(torch.sigmoid(pos_scores - neg_scores)))
        reg_embedding_loss_v = (self.v_preference[user] ** 2).mean() if self.v_preference is not None else 0.0
        reg_embedding_loss_t = (self.t_preference[user] ** 2).mean() if self.t_preference is not None else 0.0
        reg_embedding_loss_u = (self.user_embedding[user] ** 2).mean()
        reg_embedding_loss_i = (self.item_embedding[pos_items] ** 2).mean()

        reg_loss = self.reg_weight * (reg_embedding_loss_v + reg_embedding_loss_t + reg_embedding_loss_u + reg_embedding_loss_i)
        reg_loss += self.reg_weight * (self.weight_u ** 2).mean()

        return loss_value + reg_loss + self.cl_weight * cl_loss

    def cl_loss(self, view1, view2):
        view1, view2 = F.normalize(view1, dim=1), F.normalize(view2, dim=1)
        pos_score = torch.exp(torch.mul(view1, view2).sum(dim=-1) / self.temp)
        ttl_score = torch.exp(torch.matmul(view1, view2.transpose(0, 1)) / self.temp).sum(dim=1)
        cl_loss = -torch.log(pos_score / ttl_score).mean()

        return cl_loss

    def full_sort_predict(self, interaction):
        user_tensor = self.result_embed[:self.n_users]
        item_tensor = self.result_embed[self.n_users:]

        temp_user_tensor = user_tensor[interaction[0], :]
        score_matrix = torch.matmul(temp_user_tensor, item_tensor.t())
        return score_matrix

class GCN(torch.nn.Module):
    def __init__(self, datasets, batch_size, num_user, num_item, dim_id, aggr_mode, num_layer, has_id, dropout,
                 dim_latent=None, device=None, features=None):
        super(GCN, self).__init__()
        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.datasets = datasets
        self.dim_id = dim_id
        self.dim_feat = features.size(1)
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode
        self.num_layer = num_layer
        self.has_id = has_id
        self.dropout = dropout
        self.device = device

        if self.dim_latent:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
                gain=1).to(self.device))
            self.MLP = nn.Linear(self.dim_feat, 4 * self.dim_latent)
            self.MLP_1 = nn.Linear(4 * self.dim_latent, self.dim_latent)
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

        else:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_feat), dtype=torch.float32, requires_grad=True),
                gain=1).to(self.device))
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

    def forward(self, edge_index_drop, edge_index, features):
        temp_features = self.MLP_1(F.leaky_relu(self.MLP(features))) if self.dim_latent else features
        x = torch.cat((self.preference, temp_features), dim=0).to(self.device)
        x = F.normalize(x).to(self.device)

        x_hat = [x]
        for i in range (self.num_layer):
            h = self.conv_embed_1(x, edge_index)  # equation 1
            x = h
            x_hat += [x]

        x_hat = torch.stack(x_hat, dim=1)
        x_hat = x_hat.sum(dim=1, keepdim=False)
        return x_hat, self.preference, temp_features


class Base_gcn(MessagePassing):
    def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
        super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
        self.aggr = aggr
        self.in_channels = in_channels
        self.out_channels = out_channels

    def forward(self, x, edge_index, size=None):
        # pdb.set_trace()
        if size is None:
            edge_index, _ = remove_self_loops(edge_index)
            # edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
        x = x.unsqueeze(-1) if x.dim() == 1 else x
        # pdb.set_trace()
        return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x)

    def message(self, x_j, edge_index, size):
        if self.aggr == 'add':
            # pdb.set_trace()
            row, col = edge_index
            deg = degree(row, size[0], dtype=x_j.dtype)
            deg_inv_sqrt = deg.pow(-0.5)
            norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
            return norm.view(-1, 1) * x_j
        return x_j

    def update(self, aggr_out):
        return aggr_out

    def __repr(self):
        return '{}({},{})'.format(self.__class__.__name__, self.in_channels, self.out_channels)